# HIV AIDS 

The matrix below gives the probabilities of moving from 1 health state to another in 1 year.  If the current health states for a group are:
- 85% asymptomatic
- 10% symptomatic
- 5% AIDS
- 0% death

what will be the % in each health state in 1 year?

<img src="images/markov_health.jpg" alt="floating point" style="width: 50%"/>(Source: [Concepts of Markov Chains](https://www.youtube.com/watch?v=0Il-y_WLTo4))

In [1]:
# Take this vector?
# What the probabilities are 
# Group of people 85% are sympatomatic. 10% are sympotmatic. 5% are AIDS. 0% are in death

# Predict the probabilities 

In [2]:
import numpy as np

In [4]:
x = np.array([0.85, 0.10, 0.5, 0.0])

In [6]:
A = np.array([[0.90, 0.70, 0.02, 0.01],
              [0.0, 0.93, 0.05, 0.02],
              [0.0, 0.0, 0.85, 0.15],
              [0.0, 0.0, 0.0, 1.00]])

In [9]:
print(x.shape, A.shape)

(4,) (4, 4)


In [10]:
A.T @ x.T

array([0.765 , 0.688 , 0.447 , 0.0855])

In [12]:
x @ A

array([0.765 , 0.688 , 0.447 , 0.0855])

# Shop 

<img src="images/shop.png" alt="floating point" style="width: 100%"/>(Source: [Several Simple Real-world Applications of Linear Algebra Tools](https://www.mff.cuni.cz/veda/konference/wds/proc/pdf06/WDS06_106_m8_Ulrychova.pdf))

In [16]:
p1 = np.array([6.0, 5.0, 3.0, 1.0]) # 4 x 1

In [17]:
s1 = np.array([[1.50],
               [2.00],
               [5.00],
               [16.00]])

In [20]:
p1.shape

(4,)

In [18]:
p1 @ s1

array([50.])